In [1]:
import numpy as np

In [2]:
with open("input.txt", "r") as f:
    bingo_input = f.readlines()

In [6]:
chosen_numbers = bingo_input.pop(0)
chosen_numbers = chosen_numbers.split()

In [7]:
chosen_numbers

['46,79,77,45,57,34,44,13,32,88,86,82,91,97,89,1,48,31,18,10,55,74,24,11,80,78,28,37,47,17,21,61,26,85,99,96,23,70,3,54,5,41,50,63,14,64,42,36,95,52,76,68,29,9,98,35,84,83,71,49,73,58,56,66,92,30,51,20,81,69,65,15,6,16,39,43,67,7,59,40,60,4,90,72,22,0,93,94,38,53,87,27,12,2,25,19,8,62,33,75']

In [29]:
list_of_boards = []
for i in range(int(len(bingo_input)/6)):
    list_of_boards.append(np.loadtxt(bingo_input[6*i:6*(i+1)], dtype=np.int8))

In [30]:
list_of_results = [np.zeros(shape=(5,5), dtype=np.int8) for a in list_of_boards]

In [32]:
list_of_boards

[array([[84, 94, 24, 52, 44],
        [96, 33, 74, 35, 13],
        [60, 51, 41, 19, 95],
        [50, 93, 27, 40,  1],
        [67, 23, 37, 88, 85]], dtype=int8),
 array([[12, 85,  6, 97, 77],
        [79, 28, 24, 70, 51],
        [71, 72, 78, 55, 73],
        [11, 36,  5, 98, 19],
        [30, 67, 89, 95, 62]], dtype=int8),
 array([[54, 38, 70, 29, 51],
        [16, 19, 80, 96, 63],
        [76, 23, 10, 30, 24],
        [45, 81, 97, 82, 90],
        [60, 94, 28, 11, 83]], dtype=int8),
 array([[50, 56, 42, 68, 48],
        [ 6, 70, 78, 22, 27],
        [75, 11, 63, 24, 47],
        [29, 99, 91, 73, 97],
        [ 7, 16, 28, 12, 44]], dtype=int8),
 array([[20, 62, 50, 36, 12],
        [ 3, 10, 40,  8, 56],
        [78, 61, 66, 37, 89],
        [72, 26, 19, 65, 22],
        [30, 91, 27,  5, 63]], dtype=int8),
 array([[75, 91, 84,  0, 96],
        [ 1, 58, 83, 81, 20],
        [36,  8, 82, 66, 77],
        [59, 15, 71, 80, 56],
        [17, 45, 46, 26, 73]], dtype=int8),
 array([[33, 71,